spring: 
  application: 
    name:  interviewpanel-ms-user-service
  data: 
    mongodb: 
      authentication-database: admin
      username: selva
      password: selva
      database: test
      port: 27017
      host: localhost
#  kafka:
#    bootstrap-servers: localhost:9092
#    topic:
#      userCreated: USER_CREATED_TOPIC
  cloud:
     stream:
       kafka:
         binder:
           brokers:
           - http://localhost:9092
       bindings:
         output:
           destination: USER_CREATED_TOPIC     
server:
  port: 8083